require 'prime'

require 'kernel/data'
require 'object/put'
require 'numeric/math'
require 'numeric/round'
require 'numeric/square'
require 'numeric/squared'
require 'integer/divisible'
require 'integer/factors'
require 'integer/palindrome'
require 'string/palindrome'
require 'enumerable/combination'
require 'enumerable/combine'
require 'enumerable/multiply'
require 'enumerable/sum'
require 'math/phi'
require 'math/fibonacci'

require 'lazylist/list_builder/silence_warning'
