require 'prime'
require 'matrix'

require 'kernel/data'
require 'object/put'
require 'numeric/math'
require 'numeric/round'
require 'numeric/square'
require 'numeric/squared'
require 'integer/divisible'
require 'integer/factorize'
require 'integer/factors'
require 'integer/palindrome'
require 'integer/split'
require 'string/palindrome'
require 'enumerable/combination'
require 'enumerable/combine'
require 'enumerable/multiply'
require 'enumerable/sum'
require 'math/phi'
require 'math/fibonacci'
require 'matrix/minors'
require 'matrix/diagonal_vectors'
require 'matrix/star_vectors'

require 'lazylist/list_builder/silence_warning'
